name: Create Production Builds

on:
  push:
    branches: ['master']

jobs:
  build_android_dev:
    type: build # This job type creates a development build for Android
    params:
      platform: android
      profile: development
